data_paths:
  test_file: src/data/raw/test_raw.txt
  training_file: src/data/raw/train_raw.txt
  val_file: src/data/raw/val_raw.txt
params:
  batch_test: 5000
  batch_train: 5000
  categories:
  - phishing
  - legitimate
  char_index_size: 71
  dataset_dir: ../dataset/small_dataset/
  embedding_dimension: 50
  epoch: 1
  loss_function: binary_crossentropy
  optimizer: adam
  sequence_length: 200
processed_paths:
  test: src/data/processed/test
  train: src/data/processed/train
  val: src/data/processed/val
