data_paths:
  test_file: src/data/raw/test_raw.txt
  training_file: src/data/raw/train_raw.txt
  val_file: src/data/raw/val_raw.txt
params:
  batch_test: 5000
  batch_train: 5000
  categories:
  - phishing
  - legitimate
  char_index_size: 71
  dataset_dir: ../dataset/small_dataset/
  embedding_dimension: 50
  epoch: 1
  loss_function: binary_crossentropy
  optimizer: adam
  sequence_length: 200
processed_paths:
  model_path: models/phishing_model.keras
  x_test: src/data/processed/x_test.npy
  x_train: src/data/processed/x_train.npy
  x_val: src/data/processed/x_val.npy
  y_test: src/data/processed/y_test.npy
  y_train: src/data/processed/y_train.npy
  y_val: src/data/processed/y_val.npy
report_paths:
  accuracy_score: reports/accuracy.txt
  classification_report: reports/classification_report.txt
  confusion_matrix: reports/confusion_matrix.txt
  heatmap: reports/figures/confusion_matrix_heatmap.png
